// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('stay', []);

  angular.module('stay').controller('StayController', [
    '$window', function($window) {
      this.foo = 'hello';
      this.screen = {
        width: $window.screen.width,
        height: $window.screen.height
      };
      this.window = {};
      this.doit = (function(_this) {
        return function() {
          return chrome.windows.getCurrent(null, function(w) {
            return _this.window = w;
          });
        };
      })(this);
      return this;
    }
  ]);

}).call(this);
